// <auto-generated/>
#pragma warning disable CS0618
using Kanban.API.Client.Boards;
using Kanban.API.Client.ConfirmEmail;
using Kanban.API.Client.ForgotPassword;
using Kanban.API.Client.Login;
using Kanban.API.Client.Manage;
using Kanban.API.Client.Refresh;
using Kanban.API.Client.Register;
using Kanban.API.Client.ResendConfirmationEmail;
using Kanban.API.Client.ResetPassword;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kanban.API.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The boards property</summary>
        public global::Kanban.API.Client.Boards.BoardsRequestBuilder Boards
        {
            get => new global::Kanban.API.Client.Boards.BoardsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The confirmEmail property</summary>
        public global::Kanban.API.Client.ConfirmEmail.ConfirmEmailRequestBuilder ConfirmEmail
        {
            get => new global::Kanban.API.Client.ConfirmEmail.ConfirmEmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forgotPassword property</summary>
        public global::Kanban.API.Client.ForgotPassword.ForgotPasswordRequestBuilder ForgotPassword
        {
            get => new global::Kanban.API.Client.ForgotPassword.ForgotPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::Kanban.API.Client.Login.LoginRequestBuilder Login
        {
            get => new global::Kanban.API.Client.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The manage property</summary>
        public global::Kanban.API.Client.Manage.ManageRequestBuilder Manage
        {
            get => new global::Kanban.API.Client.Manage.ManageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::Kanban.API.Client.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::Kanban.API.Client.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::Kanban.API.Client.Register.RegisterRequestBuilder Register
        {
            get => new global::Kanban.API.Client.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resendConfirmationEmail property</summary>
        public global::Kanban.API.Client.ResendConfirmationEmail.ResendConfirmationEmailRequestBuilder ResendConfirmationEmail
        {
            get => new global::Kanban.API.Client.ResendConfirmationEmail.ResendConfirmationEmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resetPassword property</summary>
        public global::Kanban.API.Client.ResetPassword.ResetPasswordRequestBuilder ResetPassword
        {
            get => new global::Kanban.API.Client.ResetPassword.ResetPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kanban.API.Client.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
