// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Boards;
using ApiSdk.ConfirmEmail;
using ApiSdk.ForgotPassword;
using ApiSdk.Login;
using ApiSdk.Manage;
using ApiSdk.Refresh;
using ApiSdk.Register;
using ApiSdk.ResendConfirmationEmail;
using ApiSdk.ResetPassword;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Kanban.API.Client : BaseRequestBuilder
    {
        /// <summary>The boards property</summary>
        public global::ApiSdk.Boards.BoardsRequestBuilder Boards
        {
            get => new global::ApiSdk.Boards.BoardsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The confirmEmail property</summary>
        public global::ApiSdk.ConfirmEmail.ConfirmEmailRequestBuilder ConfirmEmail
        {
            get => new global::ApiSdk.ConfirmEmail.ConfirmEmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forgotPassword property</summary>
        public global::ApiSdk.ForgotPassword.ForgotPasswordRequestBuilder ForgotPassword
        {
            get => new global::ApiSdk.ForgotPassword.ForgotPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::ApiSdk.Login.LoginRequestBuilder Login
        {
            get => new global::ApiSdk.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The manage property</summary>
        public global::ApiSdk.Manage.ManageRequestBuilder Manage
        {
            get => new global::ApiSdk.Manage.ManageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::ApiSdk.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::ApiSdk.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::ApiSdk.Register.RegisterRequestBuilder Register
        {
            get => new global::ApiSdk.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resendConfirmationEmail property</summary>
        public global::ApiSdk.ResendConfirmationEmail.ResendConfirmationEmailRequestBuilder ResendConfirmationEmail
        {
            get => new global::ApiSdk.ResendConfirmationEmail.ResendConfirmationEmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resetPassword property</summary>
        public global::ApiSdk.ResetPassword.ResetPasswordRequestBuilder ResetPassword
        {
            get => new global::ApiSdk.ResetPassword.ResetPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Kanban.API.Client"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Kanban.API.Client(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
